version: '3'
services:
  react-app:
    image: react-app
    build: ./client/
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - mern-app
    volumes:
      - ./client/:/usr/src/app
      - ./client/node_modules:/usr/src/app/node_modules
  api-server:
    image: api-server
    build: ./server/
    ports:
      - '5000:5000'
    networks:
      - mern-app
    depends_on:
      - mongo
    volumes:
      - ./server/:/usr/src/app
      - ./server/node_modules:/usr/src/app/node_modules
  mongo:
    image: mongo:4.4-bionic
    ports:
      - '27017:27017'
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
    logging:
      driver: 'none'
    command: mongod --quiet --logpath /dev/null

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
